### ISSUE TITLE
KeyError on Project(s) Data

### ISSUE THREAD

**Issue by oxr463** [bashofmann/rancher-monitoring-v1-to-v2#6]
```
docker run bashofmann/rancher-monitoring-v1-to-v2 -- check_monitoring_disabled.py --rancher-url https://rancher.local --rancher-api-token [ . . . REDACTED . . . ] --cluster-id c-01234
Traceback (most recent call last):
File "/usr/src/app/check_monitoring_disabled.py", line 159, in <module>
check_if_monitoring_is_disabled()
File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
return callback(*args, **kwargs)
File "/usr/src/app/check_monitoring_disabled.py", line 83, in check_if_monitoring_is_disabled
for project in projects["data"]:
KeyError: 'data'
```

**Comment by bashofmann** [comment]
Sounds strange that the Rancher API does not return a list of projects. Are you running this with admin API keys, or do you only have restricted access to the cluster? Does this cluster contain any projects?

Also which Rancher version are you running this against?

**Comment by oxr463** [comment]
We checked https://rancher.local/v3/projects in the browser and saw the data section. This was an admin account and there are projects.

This was on Rancher v2.5.9.

**Comment by vasyakrg** [comment]
i have a trouble too

**Comment by bashofmann** [comment]
I tested it on 2.5.9 and the script works normally like that. Is the hostname really `rancher.local`?  The `.local` TLD is special and meant for multicast DNS and should not be used for anything else.
It could be that the docker image, the host system or your local DNS is not resolving this correctly. And the key error is just hiding this, because of missing error handling before.

I added some error handling in https://github.com/bashofmann/rancher-monitoring-v1-to-v2/commit/91ef8fc6f6b088604c7d38387f414bcaca1bf46e.

Can you test it with check in place?

**Comment by oxr463** [comment]
> I tested it on 2.5.9 and the script works normally like that. Is the hostname really `rancher.local`? The `.local` TLD is special and meant for multicast DNS and should not be used for anything else.
> It could be that the docker image, the host system or your local DNS is not resolving this correctly. And the key error is just hiding this, because of missing error handling before.

No, I just replaced the customer's URL with that as a placeholder.
